const { toStringOrNull, toNumberOrNull } = require("../utils/parse");
const { collectDescendantLocationIds } = require("./location.service");
const legacyRobotMapper = require("../engine/domain/mappers/legacyRobot");
const robotSpecification = require("./robotSpecification");
const simulationPolicy = require("../simulation/simulationPolicy");
// The commissioning-time producer for `EnergyModelParams` and `BatteryState`. See that
// module's header for why every physical coefficient it writes is null.
const agentEnergyProvisioning = require("./agentEnergyProvisioning.service");
const simulatedClassDeclaration = require("./simulatedClassDeclaration.service");

function clamp(n, min, max) {
  return Math.max(min, Math.min(max, n));
}

/**
 * The latency budget of the one commissioning transaction, in milliseconds.
 *
 * Prisma's interactive-transaction default is 5000 ms. This transaction is about twenty
 * sequential statements that must commit together (Robot, Agent, class, models,
 * capabilities and, for a simulated unit, its energy rows). Against a remote PostgreSQL
 * every statement costs a few network round trips, so at about 65 ms RTT the default
 * expired before the transaction finished. The request then answered 500 with P2028 at
 * whichever statement was running when the deadline passed, which was the final re-read.
 * There is no non-database work inside it to move out.
 *
 * Set on this transaction only, not on the client. It is still a hard bound: a
 * transaction that outlives it is rolled back and leaves no rows.
 */
const COMMISSIONING_TRANSACTION_TIMEOUT_MS = 15_000;

/**
 * Commission a **physical** unit — the service behind `POST /api/robots`.
 *
 * ── STEP 2: this endpoint no longer creates simulated robots ────────────────
 * It used to. `body.simulated: true` was accepted here, which made the physical
 * commissioning endpoint a second, unrestricted way to create a simulated unit —
 * bypassing the one-per-operator ownership rule entirely, because this path has no
 * concept of an owner. Two creation surfaces for one kind of thing, one of them
 * ungoverned, is the loophole; it is closed by making the *public entry points*
 * semantically distinct rather than by duplicating anything.
 *
 * What both paths still share is `createRobotWithProjection` below — the Robot row, the
 * `AgentClass`, the specification model rows, the `Agent`, all in one transaction. There
 * is exactly one implementation of that, and neither path has its own.
 *
 * @param {object} prisma
 * @param {object} body
 * @returns {Promise<object>} the created Robot row with its specification includes
 */
async function commissionRobot(prisma, body) {
  // ── The simulated half is refused here, by name ───────────────────────────
  //
  // Not ignored. A silently dropped `simulated: true` would create a physical robot while
  // the caller believed it had created a simulated one, and the divergence would only
  // surface later as "my simulator never starts" — the same class of silent
  // mis-provisioning `normaliseSimulatedInput` refuses coercion to avoid.
  const simulatedInput = simulationPolicy.normaliseSimulatedInput(body?.simulated);
  if (!simulatedInput.ok) {
    const err = new Error(simulatedInput.problem);
    err.status = 400;
    throw err;
  }
  if (simulatedInput.simulated === true) {
    const err = new Error(
      "This endpoint commissions physical units only. A simulated robot is created through " +
        "POST /api/simulator/robot, which assigns it to the authenticated operator and enforces " +
        "the one-simulated-robot-per-operator rule. Commissioning one here would bypass that rule.",
    );
    err.status = 400;
    err.code = "SIMULATED_NOT_ALLOWED_HERE";
    throw err;
  }

  // Ownership is derived from authentication at the simulator endpoint and is never a
  // request field anywhere. Rejected rather than ignored, for the same reason as above.
  if (body?.simulationOwnerId !== undefined) {
    const err = new Error(
      "simulationOwnerId is not a request field. Simulation ownership is derived from the " +
        "authenticated operator by POST /api/simulator/robot; physical robots have no owner.",
    );
    err.status = 400;
    err.code = "OWNER_NOT_CALLER_SUPPLIED";
    throw err;
  }

  return createRobotWithProjection(prisma, body, {
    robotCode: toStringOrNull(body?.robotId),
    simulated: false,
    simulationOwnerId: null,
  });
}

/**
 * The shared creation machinery: validate a specification, then write the Robot, its
 * `AgentClass` and model rows, and its `Agent`, in one transaction.
 *
 * Both public entry points — physical commissioning and simulated creation — call this
 * and nothing else writes those rows. The three facts that differ between the two paths
 * are parameters, not branches inside the body:
 *
 *   * `robotCode` — supplied by the operator for a physical unit, generated by the server
 *     for a simulated one (a client must not choose a simulated robot's identity).
 *   * `simulated` — the discriminator `simulationPolicy` reads.
 *   * `simulationOwnerId` — the operator who owns a simulated unit; always `null` for a
 *     physical one.
 *
 * @param {object} prisma
 * @param {object} body the creation request's remaining fields
 * @param {{ robotCode: string|null, simulated: boolean, simulationOwnerId: string|null }} identity
 * @returns {Promise<object>}
 */
async function createRobotWithProjection(prisma, body, identity) {
  const robotCode = toStringOrNull(identity?.robotCode);
  const simulated = identity?.simulated === true;
  const simulationOwnerId = toStringOrNull(identity?.simulationOwnerId);
  const locationId = toStringOrNull(body?.locationId);
  const campusId = toStringOrNull(body?.campusId);
  const latIn = toNumberOrNull(body?.lat);
  const lonIn = toNumberOrNull(body?.lon);
  const name = toStringOrNull(body?.name) || null;

  if (!robotCode || !locationId) {
    const err = new Error("robotId and locationId are required");
    err.status = 400;
    throw err;
  }

  // ── The unit's specification, validated before anything is written ────────
  //
  // The chassis type reaches the backend here rather than being dropped: it resolves to
  // an `AgentClass` (§2.1), which is what keys every model-specific parameter set, and
  // the six entered values land on the model fields that already mean them
  // (`robotSpecification.js` holds that mapping and states each destination).
  //
  // Validated before the transaction, so a rejected specification leaves no Robot row
  // behind — the same discipline `task.service.assignTask` applies to its cutover gate.
  const chassisType = robotSpecification.normaliseChassisType(body?.chassisType ?? body?.type);
  if (chassisType === null) {
    const err = new Error(
      `chassisType is required and must be one of ${robotSpecification.CHASSIS_TYPES.join(", ")}`,
    );
    err.status = 400;
    throw err;
  }

  // ── Physical or simulated, decided once, at creation ──────────────────────
  //
  // The value arrives as a parameter from whichever entry point was called, never from
  // the request body: `commissionRobot` refuses a body that mentions it and passes
  // `false`; `simulatedRobot.service` passes `true` for the endpoint that exists to
  // create one. So the discriminator is a property of *which surface was used*, which is
  // the whole point of separating them.
  //
  // Deliberately create-only. There is no path that flips an existing unit: `updateRobot`
  // enumerates its editable fields and neither `simulated` nor `simulationOwnerId` is
  // among them, so a commissioned physical robot cannot later be turned into a simulated
  // one by an API caller — which is the mutation that would hand the simulator a physical
  // unit's credentials. Changing a unit's nature means decommissioning it and creating
  // another.

  const parsed = robotSpecification.parseSpecification(body?.specification ?? body, {
    require: robotSpecification.COMMISSIONING_REQUIRED,
  });
  if (!parsed.ok) {
    const err = new Error(`Invalid robot specification: ${parsed.problems.join(" ")}`);
    err.status = 400;
    err.problems = parsed.problems;
    throw err;
  }

  // Reject duplicate robot IDs — each unit must have a unique identifier.
  const duplicate = await prisma.robot.findUnique({ where: { robotId: robotCode }, select: { id: true } });
  if (duplicate) {
    const err = new Error(`A robot with ID "${robotCode}" is already commissioned. Choose a different identifier.`);
    err.status = 409;
    // Named, so a caller can tell *which* 409 this is without reading the sentence. The
    // simulated path generates its own identifiers and treats this one as its own problem
    // (it draws another and retries); matching on the message instead would be matching on
    // prose that a translation or a reword would break.
    err.code = "ROBOT_ID_TAKEN";
    throw err;
  }

  const location = await prisma.location.findUnique({ where: { id: locationId }, select: { id: true, lat: true, lon: true } });
  if (!location) {
    const err = new Error("Invalid locationId");
    err.status = 400;
    throw err;
  }

  const lat = latIn === null ? toNumberOrNull(location.lat) : latIn;
  const lon = lonIn === null ? toNumberOrNull(location.lon) : lonIn;

  if (campusId) {
    const campus = await prisma.campus.findUnique({ where: { id: campusId }, select: { id: true } });
    if (!campus) {
      const err = new Error("Invalid campusId");
      err.status = 400;
      throw err;
    }
  }

  const now = new Date();

  const rows = robotSpecification.modelRowsFor({ robotCode, chassisType, spec: parsed.spec });

  // ── The initial state of charge is entered, never invented ────────────────
  //
  // Commissioning used to seed `battery` with `Math.round(randFloat(70, 100))`. That
  // number then travelled: it seeded the VirtualRobot's pack, it was written to the live
  // state key, it reached the dashboard, and §14.1's energy feasibility would have
  // reasoned from it. A random value presented as a measurement is a fabricated fleet
  // fact, and it is exactly the class of thing this programme refuses elsewhere.
  //
  // What replaces it is the operator's own declaration. `initialBatteryPct` is
  // **configured initial state**, not measured fleet history, and every surface that
  // shows it says so.
  //
  // P2B-2 — and it is a state only for a unit whose pack the declaration *is*. For a
  // simulated unit the simulator seeds its pack from it, so the Robot row's `battery` is the
  // pack's real starting level. For a physical unit nobody has read a pack: the declared
  // number is not a measurement, and writing it to `Robot.battery` made the dashboard (and
  // the live-state fallback in `telemetry.handler`) present it as the robot's current charge
  // until a measured report replaced it. A physical unit therefore starts with no battery
  // value at all. The declaration is still validated and still required by the
  // commissioning contract; it is simply not recorded as a reading.
  const battery = simulated ? clamp(parsed.spec.initialBatteryPct, 0, 100) : null;

  // Phase 2 (§2.1): a commissioned Robot and its domain Agent are created together.
  //
  // The alternative — create the Robot and project it later — reintroduces the
  // orphan the Phase 2 completion criterion forbids ("100 % of legacy rows
  // converted with zero orphans") the moment a robot is commissioned after the
  // backfill has run. Both writes are in one transaction because a Robot with no
  // Agent is not a state this schema admits.
  //
  // The returned shape is unchanged: the caller receives the same Robot row with
  // the same includes it received before Phase 2, so no HTTP response moves.
  const created = await prisma.$transaction(async (tx) => {
    // No `include`: inside the transaction this row only supplies `id` and `robotId`, to
    // the Agent projection and the final re-read. The re-read below carries the includes
    // the response needs, and each include here cost a round trip of its own.
    const robot = await tx.robot.create({
      data: {
        robotId: robotCode,
        name,
        locationId,
        campusId,
        status: "IDLE",
        battery,
        lat,
        lon,
        speed: 0,
        simulated,
        // NULL for every physical unit. For a simulated one this is the column the
        // partial unique index `Robot_one_simulated_per_owner` constrains, so this write
        // is where a second concurrent creation by the same operator fails — inside the
        // transaction, before any Agent or AgentClass row is committed.
        simulationOwnerId,
        // ── A newly commissioned unit is offline, because it is ────────────
        //
        // This used to be `isOnline: true`. Nothing had connected: commissioning creates a
        // record, and a record is not a session. The value was a claim about the world made
        // at the moment the world was least likely to support it, and it travelled — F13
        // reads `Robot.isOnline` as liveness, and the DTARO candidate query filters on it,
        // so a unit that had never spoken was an assignment candidate.
        //
        // Liveness now comes from the only thing that can establish it: an actual session.
        // `sockets/handlers/robot.handler.js` sets `isOnline: true` at AUTH and `false` on
        // disconnect, and the staleness sweeper in `socket.server.js` retires the rest.
        // That holds identically for a physical robot and for a simulated one — the
        // simulated agent becomes online by connecting and authenticating, exactly as
        // hardware does, rather than by having been created.
        isOnline: false,
        lastSeenAt: now,
        // The two specification values with no existing column. Everything else the
        // operator entered is written by `applySpecification` below, onto the model row
        // that already means it.
        massKg: rows.robot.massKg ?? null,
        batteryReservePct: rows.robot.batteryReservePct ?? null,
      },
    });

    // In the same transaction as the Robot and the Agent, for the same reason those two
    // share one: a unit whose class exists but whose Agent does not — or whose Agent
    // points at a class that was rolled back — is not a state this schema should admit.
    const agentClass = await applySpecification(tx, { robotCode, chassisType, spec: parsed.spec });
    const agent = await ensureAgentForRobot(tx, robot, { agentClassId: agentClass.id });

    // ── The unit's energy rows, for a simulated unit only ─────────────────
    //
    // `EnergyModelParams` and `BatteryState` have had no production producer since
    // Phase 7 created them. This is that producer, and it runs here — inside the one
    // shared commissioning transaction — rather than behind a simulator-only endpoint,
    // so a simulated unit acquires its pack state the same way it acquires its Agent.
    //
    // Gated on `simulated` for one specific reason, stated in full in the service:
    // `BatteryState.lastObservedSoc` is an **observation**, and for a simulated unit the
    // simulator is the pack so the declared level is that pack's real level, while for a
    // physical unit it would be a state of charge nobody has read off any hardware.
    // A physical unit is therefore left with no `BatteryState`, exactly as today.
    //
    // Provisioning writes `soh` and every §14.2 coefficient null. For a *simulated* unit
    // those are then filled from the simulator's own declarations (V1 demonstration,
    // 2026-09-23) — the simulator IS the pack, so its drain constants are its physics. A
    // physical unit gets neither call and keeps refusing until its model is fitted.
    if (simulated && agent && agent.id) {
      await agentEnergyProvisioning.provisionAgentEnergyState(tx, {
        agentRowId: agent.id,
        agentClassRowId: agentClass.id,
        initialBatteryPct: parsed.spec.initialBatteryPct ?? null,
        at: now,
      });
      // V1 demonstration: the simulator's own declarations (β from its drain constants,
      // SoH 1, its floor, surfaces, envelope, firmware) into the columns the engine reads.
      // DEVELOPMENT_SIMULATION values, never fitted — see simulatedClassDeclaration.service.
      await simulatedClassDeclaration.applySimulatedClassDeclaration(tx, {
        agentRowId: agent.id,
        agentClass,
        packNominalWh: rows.energy.packNominalWh,
        chassisPermissionSet: rows.mobility.permissionSet,
        payloadCapacityKg: rows.container.totalMassLimitKg,
        vehicleMassKg: rows.robot.massKg,
      });
    }

    // Re-read with the specification joined, so the response describes the unit that was
    // just created rather than the row as it looked before its class existed. Without this
    // the caller received `specification: { …all null }` for a unit it had just fully
    // configured — technically the row it created, and misleading about it.
    return tx.robot.findUnique({
      where: { id: robot.id },
      include: {
        location: true,
        campus: true,
        currentTask: true,
        ...robotSpecification.SPECIFICATION_INCLUDE,
      },
    });
  }, { timeout: COMMISSIONING_TRANSACTION_TIMEOUT_MS });

  return created;
}

/**
 * Write one unit's specification onto the model rows §2.1–§2.3 already define.
 *
 * Idempotent: every id is a deterministic function of the robot's own code
 * (`robotSpecification.modelIdsFor`), so applying a specification twice converges on the
 * same rows. That is what lets commissioning and every subsequent edit share one writer
 * instead of having a create path and an update path that can drift.
 *
 * ── Capabilities are replaced, not merged ───────────────────────────────────
 * A bundle's capability set is a statement about what the unit *is*, and merging a new
 * statement into an old one leaves capabilities nobody currently claims. The rows are
 * deleted and rewritten inside the caller's transaction, so a reader never observes a
 * bundle mid-rewrite.
 *
 * @param {object} tx a transaction client (or a Prisma client, for a single edit)
 * @param {{ robotCode: string, chassisType: string, spec: object }} input
 * @returns {Promise<object>} the `AgentClass` row
 */
async function applySpecification(tx, input) {
  const rows = robotSpecification.modelRowsFor(input);

  const mobility = await tx.mobilityModel.upsert({
    where: { modelId: rows.mobility.modelId },
    create: rows.mobility,
    update: rows.mobility,
  });

  const energy = await tx.energyModel.upsert({
    where: { modelId: rows.energy.modelId },
    create: rows.energy,
    update: rows.energy,
  });

  const container = await tx.containerModel.upsert({
    where: { modelId: rows.container.modelId },
    create: rows.container,
    update: rows.container,
  });

  // The bundle row carries no capability rows of its own on either branch; they are
  // written once below. Nesting `capabilities: { create }` in the `create` branch would
  // write them and then have the rewrite immediately delete and re-insert them — two
  // writes for one statement, and a create path that behaved differently from the update
  // path is exactly the drift this single writer exists to remove.
  const { capabilities, ...bundleFields } = rows.bundle;
  const bundle = await tx.capabilityBundle.upsert({
    where: { bundleId: bundleFields.bundleId },
    create: bundleFields,
    update: bundleFields,
  });

  // Replaced, not merged: a bundle states what the unit **is**, and merging a new
  // statement into an old one leaves capabilities nobody currently claims. Both halves are
  // in the caller's transaction, so no reader observes a bundle mid-rewrite.
  //
  // One INSERT for the whole set. It has the same rows, and `skipDuplicates` is left off,
  // so a repeated name still fails on `@@unique([bundleId, name])` and aborts the
  // transaction exactly as a per-row create did.
  await tx.capability.deleteMany({ where: { bundleId: bundle.id } });
  await tx.capability.createMany({
    data: capabilities.map((capability) => ({ ...capability, bundleId: bundle.id })),
  });

  const classFields = {
    ...rows.agentClass,
    mobilityModelId: mobility.id,
    energyModelId: energy.id,
    containerModelId: container.id,
    capabilityBundleId: bundle.id,
  };

  return tx.agentClass.upsert({
    where: { classId: classFields.classId },
    create: classFields,
    update: classFields,
  });
}

/**
 * Edit a commissioned unit's specification — the write half of `PATCH /api/robots/:robotId`.
 *
 * ── What may be edited, and what deliberately may not ───────────────────────
 * Only the unit's *configuration*: the chassis family, the six specification values, and
 * the display name. Nothing observed and nothing decided — not `status`, not `battery`,
 * not `lat`/`lon`, not `currentTaskId`, not `isOnline`. Those are either telemetry (the
 * fleet reports them) or the assignment engine's (it decides them), and an admin endpoint
 * that could set them would be an operator writing a measurement, which is the fabrication
 * this programme refuses. The controller enforces the field list; this function is the
 * second half of that fence and reads nothing outside it.
 *
 * ── Why the two speeds are re-validated against the stored row ──────────────
 * `parseSpecification` can only compare two values it was given. An edit that lowers the
 * maximum below a *stored* normal speed is the same contradiction as declaring both at
 * once, and it is only visible here, where the stored row is in hand.
 *
 * @param {object} prisma
 * @param {string} robotCode
 * @param {object} patch
 * @returns {Promise<object>} the updated Robot row, with its specification includes
 */
async function updateRobotSpecification(prisma, robotCode, patch) {
  const code = toStringOrNull(robotCode);
  if (!code) {
    const err = new Error("robotId is required");
    err.status = 400;
    throw err;
  }

  const existing = await prisma.robot.findUnique({
    where: { robotId: code },
    include: robotSpecification.SPECIFICATION_INCLUDE,
  });
  if (!existing) {
    const err = new Error("Unknown robotId");
    err.status = 404;
    throw err;
  }

  const stored = robotSpecification.specificationOf(existing);

  const chassisType =
    patch?.chassisType === undefined && patch?.type === undefined
      ? stored.chassisType
      : robotSpecification.normaliseChassisType(patch?.chassisType ?? patch?.type);

  if (chassisType === null) {
    const err = new Error(
      `chassisType must be one of ${robotSpecification.CHASSIS_TYPES.join(", ")}`,
    );
    err.status = 400;
    throw err;
  }

  const parsed = robotSpecification.parseSpecification(patch?.specification ?? patch);
  if (!parsed.ok) {
    const err = new Error(`Invalid robot specification: ${parsed.problems.join(" ")}`);
    err.status = 400;
    err.problems = parsed.problems;
    throw err;
  }

  // The effective specification: what was stored, with the edit applied over it. The
  // model rows are rewritten in full, so a partial edit must not blank the five fields it
  // did not name.
  const effective = {
    massKg: parsed.spec.massKg ?? stored.massKg ?? undefined,
    maxSpeedMps: parsed.spec.maxSpeedMps ?? stored.maxSpeedMps ?? undefined,
    normalSpeedMps: parsed.spec.normalSpeedMps ?? stored.normalSpeedMps ?? undefined,
    batteryCapacityWh: parsed.spec.batteryCapacityWh ?? stored.batteryCapacityWh ?? undefined,
    batteryReservePct: parsed.spec.batteryReservePct ?? stored.batteryReservePct ?? undefined,
    payloadCapacityKg: parsed.spec.payloadCapacityKg ?? stored.payloadCapacityKg ?? undefined,
  };

  if (
    typeof effective.normalSpeedMps === "number" &&
    typeof effective.maxSpeedMps === "number" &&
    effective.normalSpeedMps > effective.maxSpeedMps
  ) {
    const err = new Error("Invalid robot specification: Normal speed cannot exceed max speed.");
    err.status = 400;
    err.problems = ["Normal speed cannot exceed max speed."];
    throw err;
  }

  const name = patch?.name === undefined ? undefined : toStringOrNull(patch.name);

  return prisma.$transaction(async (tx) => {
    const agentClass = await applySpecification(tx, { robotCode: code, chassisType, spec: effective });

    // The Agent's class is repointed on every edit, because a chassis change is a class
    // change and an Agent left on the previous class would be priced against a parameter
    // set the unit no longer has.
    await ensureAgentForRobot(tx, existing, { agentClassId: agentClass.id });

    return tx.robot.update({
      where: { robotId: code },
      data: {
        ...(name === undefined ? {} : { name }),
        ...(typeof effective.massKg === "number" ? { massKg: effective.massKg } : {}),
        ...(typeof effective.batteryReservePct === "number"
          ? { batteryReservePct: effective.batteryReservePct }
          : {}),
      },
      include: {
        location: true,
        campus: true,
        currentTask: true,
        ...robotSpecification.SPECIFICATION_INCLUDE,
      },
    });
  });
}

/**
 * Ensure the domain `Agent` (§2.1) exists for a legacy `Robot` row. Idempotent.
 *
 * The Agent's primary key is derived deterministically from the robot's own code
 * (`engine/domain/mappers/legacyRobot.deterministicId`), so this is the same upsert
 * `tools/migrate/backfillDomain.js` performs — calling both is safe and converges
 * on identical state.
 *
 * `authorityEpoch` and `fenceCounter` are deliberately absent from the update
 * branch: both are monotone counters (§2.6, invariant I6), and a re-commission that
 * reset one would invalidate a fencing decision already taken against it.
 *
 * `agentClassId` **is** in the update branch, and it is the one field that had to be:
 * §2.1 makes the class what keys every model-specific parameter set, so an Agent left on
 * a stale class after its unit's specification changed would be priced, gated and
 * energy-modelled against numbers the unit no longer has. It is written only when the
 * caller supplies one — a caller that does not know the class must not blank it.
 *
 * @param {object} prisma a client or a transaction client
 * @param {{ id: string, robotId: string }} robot
 * @param {{ agentClassId?: string|null }} [context]
 * @returns {Promise<object|null>} the Agent row, or null when the robot is unusable
 */
async function ensureAgentForRobot(prisma, robot, context) {
  if (!prisma || !prisma.agent || !robot || !robot.robotId) return null;

  const settings = context || {};
  const agent = legacyRobotMapper.robotToAgent(robot, settings);

  const update = { agentId: agent.agentId, robotDbId: agent.robotDbId };
  if (settings.agentClassId !== undefined && settings.agentClassId !== null) {
    update.agentClassId = settings.agentClassId;
  }

  return prisma.agent.upsert({
    where: { id: agent.id },
    create: agent,
    update,
  });
}

/**
 * The domain-side read model for a robot: the legacy row joined to its Agent, in
 * the projection shape `mappers/legacyRobot.toAgentProjection` defines.
 *
 * This is the "internal read models updated to join new tables" the Phase 2 plan
 * asks for. It is not wired into any HTTP response — every legacy endpoint returns
 * exactly what it returned before Phase 2 — and exists so that a Phase 3+ consumer
 * reads the domain model through one place rather than joining ad hoc.
 *
 * @param {object} prisma
 * @param {string} robotCode the legacy `Robot.robotId`
 * @returns {Promise<object|null>}
 */
async function readAgentProjection(prisma, robotCode) {
  const code = toStringOrNull(robotCode);
  if (!code) return null;

  const robot = await prisma.robot.findUnique({
    where: { robotId: code },
    include: { agent: true },
  });

  return legacyRobotMapper.toAgentProjection(robot);
}

async function listRobots(prisma, query) {
  const { locationId, includeDescendants, campusId, isOnline, status } = query || {};

  const where = {};

  if (campusId) {
    where.campusId = String(campusId);
  } else if (locationId) {
    const rootId = String(locationId);
    const wantDesc = String(includeDescendants || "true") === "true";
    if (wantDesc) {
      const ids = await collectDescendantLocationIds(prisma, rootId);
      where.locationId = { in: ids };
    } else {
      where.locationId = rootId;
    }
  }

  if (typeof isOnline === "string") where.isOnline = isOnline === "true";
  if (status) where.status = String(status);

  return prisma.robot.findMany({
    where,
    include: {
      campus: true,
      location: true,
      currentTask: true,
      // The unit's specification travels with every list read, so the Units list, the
      // detail page and the edit form all render from one query shape rather than three
      // that can disagree about which levels of the class were joined.
      ...robotSpecification.SPECIFICATION_INCLUDE,
    },
    orderBy: [{ isOnline: "desc" }, { lastSeenAt: "desc" }],
  });
}

module.exports = {
  commissionRobot,
  // The shared creation core. Exported for `services/simulatedRobot.service.js`, which is
  // the only other caller: the simulated path needs the same Robot/AgentClass/Agent
  // transaction and must not have a second copy of it.
  createRobotWithProjection,
  COMMISSIONING_TRANSACTION_TIMEOUT_MS,
  listRobots,
  ensureAgentForRobot,
  readAgentProjection,
  applySpecification,
  updateRobotSpecification,
};
