-- Schema cleanup, stage 1 (forensic re-proof of 2026-10-05).
--
-- Removes three tables nothing has ever read or written, the two enums only they used, and
-- ten indexes no query uses. No column that holds data is touched, and no existing migration
-- is edited. Everything else the forensic audit examined (Telemetry, Event, ObstacleEvent,
-- PayloadManifest, Robot.zoneId/utilization, ...) is deliberately NOT in this migration.
--
--   Decision            zero references in src/tools/tests/seed/frontend; its modal was retired
--                       by FS-06. Decision observability is DecisionRecordA/DecisionRecordB.
--   OperatingRegime     regimes are resolved from ConfigVersion.payload.regimes.
--   PackingResultCache  the §15.3 tier-4 memo is the KV key engine:pack:* (packing.js).
--
-- Preconditions, checked read-only on production immediately before applying (2026-10-05:
-- Neon returned 0 / 0 / 0):
--   SELECT count(*) FROM "Decision";            -- 0
--   SELECT count(*) FROM "OperatingRegime";     -- 0
--   SELECT count(*) FROM "PackingResultCache";  -- 0
--
-- Plain DROP, never CASCADE: no view, routine or foreign key references any of these
-- objects, so an unexpected dependent makes this migration fail instead of silently taking
-- the dependent with it.
--
-- NOT generated by `prisma migrate diff`. Diff also proposes
--   ALTER TABLE "ConfigActiveVersion" DROP CONSTRAINT "ConfigActiveVersion_version_fkey";
-- That foreign key is intentional — it guarantees the pinned active version exists — and is
-- declared only in 20260728093000_config_registry_and_governance, not in schema.prisma. It
-- is not dropped here, and must never be.
--
-- Deployment order: ship the application build without these models FIRST, then apply this
-- migration. src/db/schemaDrift.js refuses to boot a build whose client expects columns the
-- database lacks, so the old build refuses this database (DATABASE_SCHEMA_BEHIND) while the
-- new build boots on either. Rollback: run prisma/rollback/20261005180000_schema_cleanup_stage1.sql
-- (it recreates every object from its original DDL) BEFORE rolling application code back.
--
-- Robot indexes: dropped plainly, not CONCURRENTLY. CONCURRENTLY cannot run inside the
-- transaction a migration script executes in, and the Robot table is a small fleet table,
-- so the ACCESS EXCLUSIVE lock is momentary.

-- 1. Dead tables and the enums only they used ---------------------------------------------
DROP TABLE "Decision";
DROP TYPE "DecisionAction";
DROP TABLE "OperatingRegime";
DROP TYPE "OperatingRegimeState";
DROP TABLE "PackingResultCache";

-- 2. Left-prefix-redundant indexes: each column is the leading column of a btree that stays,
--    and the planner was shown to use that btree for every access pattern (equality, IN,
--    ORDER BY, and the foreign-key lock lookup).
DROP INDEX "Robot_locationId_idx";               -- Robot_locationId_isOnline_idx
DROP INDEX "Compartment_containerModelId_idx";   -- Compartment_containerModelId_ordinal_key
DROP INDEX "Capability_bundleId_idx";            -- Capability_bundleId_name_key
DROP INDEX "Leg_missionId_idx";                  -- Leg_missionId_sequence_key
DROP INDEX "Stop_legId_idx";                     -- Stop_legId_sequence_key
DROP INDEX "EnergyModelParams_agentClassId_idx"; -- EnergyModelParams_agentClassId_modelVersion_key
DROP INDEX "ServiceTimeModel_version_idx";       -- ServiceTimeModel_version_siteId_stopType_missionClass_hourO_key
DROP INDEX "ZonePriceSnapshot_version_idx";      -- ZonePriceSnapshot_version_zoneId_bucket_key
DROP INDEX "LadderEscalation_legId_idx";         -- LadderEscalation_legId_step_key

-- 3. An index no query uses: nothing filters or orders Robot by lat/lon, and the index was
--    rewritten on every position flush.
DROP INDEX "Robot_lat_lon_idx";
